import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/global.scss'
import Navbar from '@/components/navbar'
import dynamic from 'next/dynamic'
import ReduxProvider from './redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

const Footer = dynamic(() => import('@/components/footer'), {
	ssr: false
})

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ReduxProvider>
					<Navbar />
					{children}
					<Footer />
				</ReduxProvider>
			</body>
		</html>
	)
}
